# -*- coding: utf-8 -*-
"""PYTHON CYCLE 2*.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W_oY-THqUIsPaEuVj_xmCVr7IGoPmLLj
"""

s=int(input("enter starting year: "))
e=int(input("enter ending year: "))
print("leap years between",s,"and",e)
while (s<=e):
    if ((s%400==0) or ((s%4==0) and (s%100!=0))):
      print(s)
    s=s+1

x=[]
n=int(input("enter list items : "))
for i in range(1,n+1):
    a=int(input("enter the value of %d item : "%i))
    x.append(a)
y=[num for num in x if num >= 0]
print("initial list of integers is :",x) 
print("modified list of positive numbers is :",y)

w=input("enter any word : ")
v=[l for l in w if l in 'aeiou' ]
print("list of vowels in",w," :",v)

w=input("enter any word : ")
for l in range(len(w)) :
  print("ASCII value is",w[l],"is",ord(w[l]))

def word_count(str):
    counts = dict()
    words = str.split()
    for word in words:
        if word in counts:
            counts[word] += 1
        else:
            counts[word] = 1
    return counts
str=input("enter any text :")
print(word_count(str))

x=[]
n=int(input("enter any integers :"))
for i in range(1,n+1):
  a=int(input())
  if (a>100):
    x.append('over')
  else:
    x.append(a)
print("modified list :" ,x)6

def change(str):
      return str[-1:] + str[1:-1] + str[:1]
str=input("enter any string : ")
print("modified string : ",change(str))

r=int(input("enter the radius of the circle :"))
print("area of the circle is :",3.14*r*r)

a = float(input("enter the first value : "))
b = float(input("enter the second value : "))
c = float(input("enter the third value : "))
if (a > b and a > c):
  print(a,"is bigger than both",b,"and",c)
elif (b > a and b > c):
  print(b,"is bigger than both",a,"and",c)
elif (c > a and c > b):
  print(c,"is bigger than both",a,"and",b)
else:
  print("either any two values or all the three values are equal")

f=input("enter any filename : ")
x=f.split(".")
print("extension of file is",x[-1])

k1=input("enter first key : ")
k2=input("enter second key : ")
v1=input("enter first value : ")
v2=input("enter second value : ")
dict1={}
dict2={}
dict1[k1]=v1
dict2[k2]=v2
def merge_dictionaries(x,y):
  z = {**x,**y}
  print("merged dictionary is : ")
  return z
print(merge_dictionaries(dict1,dict2))

n1=float(input("enter the first value : "))
n2=float(input("enter the second value : "))
x=n1
y=n2
while (n2 != 0):
  temp=n2
  n2=n1%n2
  n1=temp
gcd=n1   
print("GCD of",x,"and",y,"is",gcd)

x=[]
n=int(input("enter list items : "))
for i in range(1,n+1):
    a=int(input("enter the value of %d item : "%i))
    x.append(a)
for i  in x:
  if (i%2 == 0):
    x.remove(i)
print("modified list after removing even numbers :")
print(x)